// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

const TableNameCache = "cache"

// Cache mapped from table <cache>
type Cache struct {
	Key        string `gorm:"column:key;type:varchar(255);primaryKey" json:"key"`
	Value      string `gorm:"column:value;type:mediumtext;not null" json:"value"`
	Expiration int32  `gorm:"column:expiration;type:int;not null" json:"expiration"`
}

// TableName Cache's table name
func (*Cache) TableName() string {
	return TableNameCache
}
