// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

const TableNameCacheLock = "cache_locks"

// CacheLock mapped from table <cache_locks>
type CacheLock struct {
	Key        string `gorm:"column:key;type:varchar(255);primaryKey" json:"key"`
	Owner      string `gorm:"column:owner;type:varchar(255);not null" json:"owner"`
	Expiration int32  `gorm:"column:expiration;type:int;not null" json:"expiration"`
}

// TableName CacheLock's table name
func (*CacheLock) TableName() string {
	return TableNameCacheLock
}
