// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

import (
	"time"
)

const TableNameFailedJob = "failed_jobs"

// FailedJob mapped from table <failed_jobs>
type FailedJob struct {
	ID         int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	UUID       string    `gorm:"column:uuid;type:varchar(255);not null;uniqueIndex:failed_jobs_uuid_unique,priority:1" json:"uuid"`
	Connection string    `gorm:"column:connection;type:text;not null" json:"connection"`
	Queue      string    `gorm:"column:queue;type:text;not null" json:"queue"`
	Payload    string    `gorm:"column:payload;type:longtext;not null" json:"payload"`
	Exception  string    `gorm:"column:exception;type:longtext;not null" json:"exception"`
	FailedAt   time.Time `gorm:"column:failed_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"failed_at"`
}

// TableName FailedJob's table name
func (*FailedJob) TableName() string {
	return TableNameFailedJob
}
