// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

const TableNameJobBatch = "job_batches"

// JobBatch mapped from table <job_batches>
type JobBatch struct {
	ID           string `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`
	Name         string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	TotalJobs    int32  `gorm:"column:total_jobs;type:int;not null" json:"total_jobs"`
	PendingJobs  int32  `gorm:"column:pending_jobs;type:int;not null" json:"pending_jobs"`
	FailedJobs   int32  `gorm:"column:failed_jobs;type:int;not null" json:"failed_jobs"`
	FailedJobIds string `gorm:"column:failed_job_ids;type:longtext;not null" json:"failed_job_ids"`
	Options      string `gorm:"column:options;type:mediumtext" json:"options"`
	CancelledAt  int32  `gorm:"column:cancelled_at;type:int" json:"cancelled_at"`
	CreatedAt    int32  `gorm:"column:created_at;type:int;not null" json:"created_at"`
	FinishedAt   int32  `gorm:"column:finished_at;type:int" json:"finished_at"`
}

// TableName JobBatch's table name
func (*JobBatch) TableName() string {
	return TableNameJobBatch
}
