// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

const TableNameJob = "jobs"

// Job mapped from table <jobs>
type Job struct {
	ID          int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Queue       string `gorm:"column:queue;type:varchar(255);not null;index:jobs_queue_index,priority:1" json:"queue"`
	Payload     string `gorm:"column:payload;type:longtext;not null" json:"payload"`
	Attempts    int32  `gorm:"column:attempts;type:tinyint unsigned;not null" json:"attempts"`
	ReservedAt  int32  `gorm:"column:reserved_at;type:int unsigned" json:"reserved_at"`
	AvailableAt int32  `gorm:"column:available_at;type:int unsigned;not null" json:"available_at"`
	CreatedAt   int32  `gorm:"column:created_at;type:int unsigned;not null" json:"created_at"`
}

// TableName Job's table name
func (*Job) TableName() string {
	return TableNameJob
}
