// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

const TableNameMigration = "migrations"

// Migration mapped from table <migrations>
type Migration struct {
	ID        int32  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Migration string `gorm:"column:migration;type:varchar(255);not null" json:"migration"`
	Batch     int32  `gorm:"column:batch;type:int;not null" json:"batch"`
}

// TableName Migration's table name
func (*Migration) TableName() string {
	return TableNameMigration
}
