// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

import (
	"time"
)

const TableNameProblem = "Problems"

// Problem mapped from table <Problems>
type Problem struct {
	ID          string    `gorm:"column:id;type:char(36);primaryKey;default:uuid()" json:"id"`
	Name        string    `gorm:"column:name;type:varchar(255);not null;index:idx_problems_name,priority:1" json:"name"`
	Content     string    `gorm:"column:content;type:text;not null" json:"content"`
	CreatedAt   time.Time `gorm:"column:created_at;type:datetime;index:idx_problems_created_at,priority:1;default:CURRENT_TIMESTAMP" json:"created_at"`
	Difficulty  string    `gorm:"column:difficulty;type:varchar(255);not null;default:easy" json:"difficulty"`
	TimeLimit   int32     `gorm:"column:time_limit;type:int;not null;default:1000" json:"time_limit"`
	MemoryLimit int32     `gorm:"column:memory_limit;type:int;not null;default:128" json:"memory_limit"`
	IsPublic    bool      `gorm:"column:is_public;type:tinyint(1);not null;default:1" json:"is_public"`
}

// TableName Problem's table name
func (*Problem) TableName() string {
	return TableNameProblem
}
