// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

const TableNameSession = "sessions"

// Session mapped from table <sessions>
type Session struct {
	ID           string `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`
	UserID       string `gorm:"column:user_id;type:varchar(255);index:sessions_user_id_index,priority:1" json:"user_id"`
	IPAddress    string `gorm:"column:ip_address;type:varchar(45)" json:"ip_address"`
	UserAgent    string `gorm:"column:user_agent;type:text" json:"user_agent"`
	Payload      string `gorm:"column:payload;type:text;not null" json:"payload"`
	LastActivity int32  `gorm:"column:last_activity;type:int;not null;index:sessions_last_activity_index,priority:1" json:"last_activity"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
