// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"judge/dbmodel"
)

func newSubmission(db *gorm.DB, opts ...gen.DOOption) submission {
	_submission := submission{}

	_submission.submissionDo.UseDB(db, opts...)
	_submission.submissionDo.UseModel(&dbmodel.Submission{})

	tableName := _submission.submissionDo.TableName()
	_submission.ALL = field.NewAsterisk(tableName)
	_submission.ID = field.NewInt64(tableName, "id")
	_submission.UserID = field.NewString(tableName, "user_id")
	_submission.ProblemID = field.NewString(tableName, "problem_id")
	_submission.Code = field.NewString(tableName, "code")
	_submission.Language = field.NewString(tableName, "language")
	_submission.Status = field.NewString(tableName, "status")
	_submission.Score = field.NewInt32(tableName, "score")
	_submission.SubmittedAt = field.NewTime(tableName, "submitted_at")
	_submission.ExecutionTime = field.NewInt32(tableName, "execution_time")
	_submission.MemoryUsed = field.NewInt32(tableName, "memory_used")
	_submission.ErrorMessage = field.NewString(tableName, "error_message")

	_submission.fillFieldMap()

	return _submission
}

type submission struct {
	submissionDo submissionDo

	ALL           field.Asterisk
	ID            field.Int64
	UserID        field.String
	ProblemID     field.String
	Code          field.String
	Language      field.String
	Status        field.String
	Score         field.Int32
	SubmittedAt   field.Time
	ExecutionTime field.Int32
	MemoryUsed    field.Int32
	ErrorMessage  field.String

	fieldMap map[string]field.Expr
}

func (s submission) Table(newTableName string) *submission {
	s.submissionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s submission) As(alias string) *submission {
	s.submissionDo.DO = *(s.submissionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *submission) updateTableName(table string) *submission {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.UserID = field.NewString(table, "user_id")
	s.ProblemID = field.NewString(table, "problem_id")
	s.Code = field.NewString(table, "code")
	s.Language = field.NewString(table, "language")
	s.Status = field.NewString(table, "status")
	s.Score = field.NewInt32(table, "score")
	s.SubmittedAt = field.NewTime(table, "submitted_at")
	s.ExecutionTime = field.NewInt32(table, "execution_time")
	s.MemoryUsed = field.NewInt32(table, "memory_used")
	s.ErrorMessage = field.NewString(table, "error_message")

	s.fillFieldMap()

	return s
}

func (s *submission) WithContext(ctx context.Context) *submissionDo {
	return s.submissionDo.WithContext(ctx)
}

func (s submission) TableName() string { return s.submissionDo.TableName() }

func (s submission) Alias() string { return s.submissionDo.Alias() }

func (s submission) Columns(cols ...field.Expr) gen.Columns { return s.submissionDo.Columns(cols...) }

func (s *submission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *submission) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["problem_id"] = s.ProblemID
	s.fieldMap["code"] = s.Code
	s.fieldMap["language"] = s.Language
	s.fieldMap["status"] = s.Status
	s.fieldMap["score"] = s.Score
	s.fieldMap["submitted_at"] = s.SubmittedAt
	s.fieldMap["execution_time"] = s.ExecutionTime
	s.fieldMap["memory_used"] = s.MemoryUsed
	s.fieldMap["error_message"] = s.ErrorMessage
}

func (s submission) clone(db *gorm.DB) submission {
	s.submissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s submission) replaceDB(db *gorm.DB) submission {
	s.submissionDo.ReplaceDB(db)
	return s
}

type submissionDo struct{ gen.DO }

func (s submissionDo) Debug() *submissionDo {
	return s.withDO(s.DO.Debug())
}

func (s submissionDo) WithContext(ctx context.Context) *submissionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s submissionDo) ReadDB() *submissionDo {
	return s.Clauses(dbresolver.Read)
}

func (s submissionDo) WriteDB() *submissionDo {
	return s.Clauses(dbresolver.Write)
}

func (s submissionDo) Session(config *gorm.Session) *submissionDo {
	return s.withDO(s.DO.Session(config))
}

func (s submissionDo) Clauses(conds ...clause.Expression) *submissionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s submissionDo) Returning(value interface{}, columns ...string) *submissionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s submissionDo) Not(conds ...gen.Condition) *submissionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s submissionDo) Or(conds ...gen.Condition) *submissionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s submissionDo) Select(conds ...field.Expr) *submissionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s submissionDo) Where(conds ...gen.Condition) *submissionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s submissionDo) Order(conds ...field.Expr) *submissionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s submissionDo) Distinct(cols ...field.Expr) *submissionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s submissionDo) Omit(cols ...field.Expr) *submissionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s submissionDo) Join(table schema.Tabler, on ...field.Expr) *submissionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s submissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *submissionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s submissionDo) RightJoin(table schema.Tabler, on ...field.Expr) *submissionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s submissionDo) Group(cols ...field.Expr) *submissionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s submissionDo) Having(conds ...gen.Condition) *submissionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s submissionDo) Limit(limit int) *submissionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s submissionDo) Offset(offset int) *submissionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s submissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *submissionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s submissionDo) Unscoped() *submissionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s submissionDo) Create(values ...*dbmodel.Submission) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s submissionDo) CreateInBatches(values []*dbmodel.Submission, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s submissionDo) Save(values ...*dbmodel.Submission) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s submissionDo) First() (*dbmodel.Submission, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodel.Submission), nil
	}
}

func (s submissionDo) Take() (*dbmodel.Submission, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodel.Submission), nil
	}
}

func (s submissionDo) Last() (*dbmodel.Submission, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodel.Submission), nil
	}
}

func (s submissionDo) Find() ([]*dbmodel.Submission, error) {
	result, err := s.DO.Find()
	return result.([]*dbmodel.Submission), err
}

func (s submissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbmodel.Submission, err error) {
	buf := make([]*dbmodel.Submission, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s submissionDo) FindInBatches(result *[]*dbmodel.Submission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s submissionDo) Attrs(attrs ...field.AssignExpr) *submissionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s submissionDo) Assign(attrs ...field.AssignExpr) *submissionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s submissionDo) Joins(fields ...field.RelationField) *submissionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s submissionDo) Preload(fields ...field.RelationField) *submissionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s submissionDo) FirstOrInit() (*dbmodel.Submission, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodel.Submission), nil
	}
}

func (s submissionDo) FirstOrCreate() (*dbmodel.Submission, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodel.Submission), nil
	}
}

func (s submissionDo) FindByPage(offset int, limit int) (result []*dbmodel.Submission, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s submissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s submissionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s submissionDo) Delete(models ...*dbmodel.Submission) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *submissionDo) withDO(do gen.Dao) *submissionDo {
	s.DO = *do.(*gen.DO)
	return s
}
