// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

import (
	"time"
)

const TableNameSubmissionTestcase = "SubmissionTestcases"

// SubmissionTestcase mapped from table <SubmissionTestcases>
type SubmissionTestcase struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	SubmissionID  int64     `gorm:"column:submission_id;type:bigint;not null;index:idx_submission_id,priority:1;index:idx_submission_status,priority:1" json:"submission_id"`
	TestcaseName  string    `gorm:"column:testcase_name;type:varchar(100);not null" json:"testcase_name"`
	Status        string    `gorm:"column:status;type:varchar(20);not null;index:idx_submission_status,priority:2;default:Pending" json:"status"`
	ExecutionTime int32     `gorm:"column:execution_time;type:int" json:"execution_time"`
	MemoryUsed    int32     `gorm:"column:memory_used;type:int" json:"memory_used"`
	Output        string    `gorm:"column:output;type:text" json:"output"`
	ErrorMessage  string    `gorm:"column:error_message;type:text" json:"error_message"`
	Score         int32     `gorm:"column:score;type:int" json:"score"`
	JudgedAt      time.Time `gorm:"column:judged_at;type:datetime;default:CURRENT_TIMESTAMP" json:"judged_at"`
}

// TableName SubmissionTestcase's table name
func (*SubmissionTestcase) TableName() string {
	return TableNameSubmissionTestcase
}
