// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodel

import (
	"time"
)

const TableNameUser = "Users"

// User mapped from table <Users>
type User struct {
	ID              string    `gorm:"column:id;type:char(36);primaryKey;default:uuid()" json:"id"`
	Username        string    `gorm:"column:username;type:varchar(50);not null;uniqueIndex:idx_users_username,priority:1;uniqueIndex:username,priority:1" json:"username"`
	Email           string    `gorm:"column:email;type:varchar(100);not null;uniqueIndex:email,priority:1;uniqueIndex:idx_users_email,priority:1" json:"email"`
	Password        string    `gorm:"column:password;type:varchar(255);not null" json:"password"`
	CreatedAt       time.Time `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP" json:"created_at"`
	EmailVerifiedAt time.Time `gorm:"column:email_verified_at;type:timestamp" json:"email_verified_at"`
	RememberToken   string    `gorm:"column:remember_token;type:varchar(100)" json:"remember_token"`
	UpdatedAt       time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
	IsAdmin         bool      `gorm:"column:is_admin;type:tinyint(1);not null" json:"is_admin"`
	IsActive        bool      `gorm:"column:is_active;type:tinyint(1);not null;default:1" json:"is_active"`
	Avatar          string    `gorm:"column:avatar;type:varchar(255)" json:"avatar"`
	Bio             string    `gorm:"column:bio;type:text" json:"bio"`
	LastLoginIP     string    `gorm:"column:last_login_ip;type:varchar(255)" json:"last_login_ip"`
	LastLoginAt     time.Time `gorm:"column:last_login_at;type:timestamp" json:"last_login_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
